bodyparts:
- eye
- nose
- mouth
- hand
- nonreachhand
- spout
- corner

start: 0
stop: 1
numframes2pick: 150

    # Plotting configuration
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.6
dotsize: 5
alphavalue: 0.7
colormap: plasma
