Label:
digin100016,laserPulseTimes
digin101024,frameTimes
digin100004,beamBreakTimes
digin100256,reward
digin108192,trigger
Trigger:
nex.Rename(doc, doc["frameTimes"], "frameTimesOrig")
doc["frameBurstOnsets"] = nex.ISIFilter(doc["frameTimesOrig"], 0.1)
doc["saveStartTime"] = nex.SelectTrials(doc["frameBurstOnsets"], "2")
doc["frameTimes"] = nex.Sync(doc["frameTimesOrig"], doc["saveStartTime"], -0.01, 10000)

frameTimes = doc["frameTimes"].Timestamps()
if frameTimes[1] > frameTimes[0] + 0.015:
    frameTimes.pop(0)
frameTimesPost = [v for i, v in enumerate(doc["frameTimes"].Timestamps()) if i in savedFrames]
doc["frameTimesPrior"] = nex.NewEvent(doc, 0)
doc["frameTimesPrior"].SetTimestamps(frameTimes)
doc["frameTimes"].SetTimestamps(frameTimesPost)